/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package queue;

import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author shamkh
 */
public class model1 extends javax.swing.JFrame {

    /**
     * Creates new form model1
     */
    public model1() {
        initComponents();

    }

    double lmda, mue, k, t, noft, n, m;
    String res_ti;
    String res_ti2;

    //---------------------------------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        arraival_rate = new javax.swing.JTextField();
        service_rate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        k_txt = new javax.swing.JTextField();
        t_txt1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nofcustomer_txt2 = new javax.swing.JTextField();
        calculate_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ti_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        wq_txt3 = new javax.swing.JTextField();
        M_txt3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nt1_txt1 = new javax.swing.JTextField();
        clearbtn = new javax.swing.JButton();
        graph_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("D/D/1/K-1");

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 1, 16)); // NOI18N
        jLabel1.setText("Arrival rate (λ)  :");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Ubuntu Light", 1, 16)); // NOI18N
        jLabel2.setText("Service rate (μ) :");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        arraival_rate.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        arraival_rate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        service_rate.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        service_rate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Ubuntu Light", 1, 16)); // NOI18N
        jLabel3.setText("(K) :");
        jLabel3.setAlignmentX(0.5F);
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Ubuntu Light", 1, 16)); // NOI18N
        jLabel4.setText("(t) :");
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        k_txt.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        k_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        t_txt1.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        t_txt1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Ubuntu Light", 1, 16)); // NOI18N
        jLabel5.setText("(n) :");
        jLabel5.setAlignmentX(0.5F);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        nofcustomer_txt2.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        nofcustomer_txt2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        calculate_btn.setFont(new java.awt.Font("Umpush", 1, 18)); // NOI18N
        calculate_btn.setText("Calculate ");
        calculate_btn.setAlignmentX(0.5F);
        calculate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate_btnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu Light", 1, 16)); // NOI18N
        jLabel6.setText("(ti) :");

        ti_txt.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Ubuntu Light", 1, 16)); // NOI18N
        jLabel7.setText("Wq(n) :");

        wq_txt3.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N

        M_txt3.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        M_txt3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        M_txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_txt3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu Light", 1, 16)); // NOI18N
        jLabel8.setText("(M) :");
        jLabel8.setAlignmentX(0.5F);
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setFont(new java.awt.Font("Ubuntu Light", 1, 16)); // NOI18N
        jLabel9.setText("n(t) : ");

        nt1_txt1.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N

        clearbtn.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        clearbtn.setForeground(java.awt.Color.red);
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        graph_btn.setFont(new java.awt.Font("Umpush", 1, 18)); // NOI18N
        graph_btn.setText("Graph");
        graph_btn.setAlignmentX(0.5F);
        graph_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graph_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ti_txt)
                            .addComponent(wq_txt3)
                            .addComponent(nt1_txt1))
                        .addGap(84, 84, 84)
                        .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(arraival_rate, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(service_rate, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(nofcustomer_txt2))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(M_txt3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(k_txt))
                        .addContainerGap(93, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(calculate_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(graph_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arraival_rate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(service_rate)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_txt1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(k_txt)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(M_txt3))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nofcustomer_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculate_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(graph_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ti_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nt1_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wq_txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate_btnActionPerformed
        // TODO add your handling code here:
        // Inputs
        String s_l = arraival_rate.getText();
        String s_m = service_rate.getText();
        String s_t = t_txt1.getText();
        String s_k = k_txt.getText();
        String s_n = nofcustomer_txt2.getText();
        String s_M = M_txt3.getText();

        double n_st = Double.parseDouble(s_t);
        double n_sk = Double.parseDouble(s_k);
        double n_sn = Double.parseDouble(s_n);
        double n_sM = Double.parseDouble(s_M);

        if (!s_l.contains("/") && !s_l.contains(".")) {
            lmda = Double.parseDouble(s_l);
        }
        if (!s_m.contains("/") && !s_m.contains(".")) {
            mue = Double.parseDouble(s_m);
        } else {
            Inputs in = new Inputs();
            lmda = in.ConvertInput(s_l);
            mue = in.ConvertInput(s_m);
        }
        if ((lmda == 0 || lmda < 0) || (mue == 0 || mue < 0) || (n_st == 0 || n_st < 0) || (n_sk == 0 || n_sk < 0) || (n_sn == 0 || n_sn < 0) || (n_sM < 0)) {
            Invalid_Inputs n = new Invalid_Inputs();
            n.setVisible(true);
            n.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            n.setLocationRelativeTo(null);
        } else {

            k = n_sk;
            t = n_st;
            n = n_sn;
            m = n_sM;
            noft = Math.floor((lmda * t) - ((mue * t) - (mue / lmda)));

            // Case 1 : λ > μ
            if (lmda > mue) {
                int ti = (int) ((k - (mue / lmda)) / (lmda - mue));
                int i;
                // trial  and error
                for (i = 0; i < ti; i++) {
                    if (k == Math.floor(i / (1 / lmda)) - Math.floor((i / (1 / mue)) - ((1 / lmda) / (1 / mue)))) {
                        break;
                    }
                }
                ti = i;
                res_ti = Integer.toString(ti);
                ti_txt.setText("By trial and error, ti = " + res_ti);

                if (1 / lmda % 1 / mue == 0) {
                    if (t < 1 / lmda) {
                        nt1_txt1.setText("t<1/λ   so  n(t) = 0");
                    } else if (t > 1 / lmda && t <= ti) {
                        nt1_txt1.setText("n(t)=|λti|-|μti-μ/λ| = " + noft);
                    } else {
                        nt1_txt1.setText("n(t)= k-1 = " + (k - 1));
                    }
                } else {
                    if (t < 1 / lmda) {
                        nt1_txt1.setText("t<1/λ   so  n(t) = 0");
                    } else if (t > 1 / lmda && t <= ti) {
                        nt1_txt1.setText("n(t)=|λti|-|μti-μ/λ| = " + noft);
                    }
                }
                if (n < lmda * ti) {
                    wq_txt3.setText("n<λti   so Wq(n) = " + ((1 / mue) - (1 / lmda)) * (n - 1));
                } else {
                    wq_txt3.setText("n>=λti   so Wq(n) = " + ((1 / mue) - (1 / lmda)) * (lmda * ti - 2));
                }

            } // Case 2 : μ >= λ
            else {
                if (lmda == mue) {
                    ti_txt.setText("μ=λ so   ti = 0");
                    nt1_txt1.setText("μ=λ so  n(t) = " + m);
                    wq_txt3.setText("μ=λ so  Wq(n) = (M-1)(1/μ) = " + ((m - 1) * (1 / mue)));
                }
                if (lmda < mue) {
                    int ti = (int) (m / (mue - lmda));
                    int i;
                    for (i = 0; i < ti; i++) {
                        if (m == Math.floor(i / (1 / mue)) - Math.floor(i / (1 / mue))) {
                            break;
                        }
                    }
                    ti = i;
                    res_ti2 = Integer.toString(ti);
                    ti_txt.setText("By trial and error, ti = " + res_ti2);
                    if (t < ti) {
                        nt1_txt1.setText("t<ti so n(t)=M+|λt|-|μt|  = " + ((m + Math.floor(lmda * t) - Math.floor(mue * t))));
                    } else {
                        nt1_txt1.setText("t>=ti so  n(t) = 0 or 1 ");
                    }
                    if (n == 0) {
                        wq_txt3.setText("((M-1)/2μ)= " + (int) Math.floor((m - 1) / (2 * mue)));
                    } else if (n < (int) Math.floor(lmda * ti)) {
                        wq_txt3.setText("Wq(n) = (M-1+n)(1/μ)-(n/λ) = " + (((m - 1 + n) * ((1 / mue)) - (n * 1 / lmda))));
                    } else {
                        wq_txt3.setText(" n<=λti  so  Wq(n) = 0");
                    }
                }

            }
        }
    }//GEN-LAST:event_calculate_btnActionPerformed

    private void M_txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_M_txt3ActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
        arraival_rate.setText("");
        service_rate.setText("");
        k_txt.setText("");
        t_txt1.setText("");
        nofcustomer_txt2.setText("");
        nt1_txt1.setText("");
        M_txt3.setText("");
        ti_txt.setText("");
        wq_txt3.setText("");

    }//GEN-LAST:event_clearbtnActionPerformed

    private void graph_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graph_btnActionPerformed
        // TODO add your handling code here:
        String s_l = arraival_rate.getText();
        String s_m = service_rate.getText();
        String s_M = M_txt3.getText();
        String s_k = k_txt.getText();
        double n_sM = Double.parseDouble(s_M);
        double n_sk = Double.parseDouble(s_k);
        k = n_sk;
        m = n_sM;
        Inputs in = new Inputs();
        lmda = in.ConvertInput(s_l);
        mue = in.ConvertInput(s_m);

        //Graph
        XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries series1 = new XYSeries("D/D/1/K-1");

        if (lmda > mue) {
            for (int i = 0; i <= Integer.parseInt(res_ti) + 10; i++) {
                if (1 / lmda % 1 / mue == 0) {
                    if (i <= 1 / lmda) {
                        series1.add(i, 0);
                    } else if (i > 1 / lmda && i <= Integer.parseInt(res_ti)) {
                        series1.add(i, Math.floor((lmda * i) - ((mue * i) - (mue / lmda))));
                    } else {
                        series1.add(i, k - 1);
                    }
                } else {
                    if (i < 1 / lmda) {
                        series1.add(i, 0);
                    } else if (i >= 1 / lmda && i < Integer.parseInt(res_ti)) {
                        series1.add(i, Math.floor((lmda * i) - ((mue * i) - (mue / lmda))));
                    }
                }
            }

        } else {
            for (int i = 0; i <= Integer.parseInt(res_ti2) + 10; i++) {
                if (lmda < mue) {
                    if (i < Integer.parseInt(res_ti2)) {
                        series1.add(i, (m + Math.floor(lmda * i) - Math.floor(mue * i)));
                    } else {
                        for (int j = i; j <= i + (1 / mue); j++) {
                            series1.add(j, 0);
                        }
                        i += 1 / mue + 1;
                        series1.add(i, 1);

                    }
                }

            }
        }

        dataset.addSeries(series1);
        JFreeChart chart = ChartFactory.createXYStepAreaChart(
                "Graph Queuery", // Chart Title
                "Time t ", // X-Axis Label
                "Number of customers", // Y-Axis Label
                dataset);

        XYPlot plot = (XYPlot) chart.getPlot();
        plot.setBackgroundPaint(new Color(229, 150, 97, 60));

        ChartPanel panel = new ChartPanel(chart);
        setContentPane(panel);
        this.setVisible(true);


    }//GEN-LAST:event_graph_btnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(model1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(model1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(model1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(model1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //launch(args);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new model1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField M_txt3;
    private javax.swing.JTextField arraival_rate;
    private javax.swing.JButton calculate_btn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton graph_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField k_txt;
    private javax.swing.JTextField nofcustomer_txt2;
    private javax.swing.JTextField nt1_txt1;
    private javax.swing.JTextField service_rate;
    private javax.swing.JTextField t_txt1;
    private javax.swing.JTextField ti_txt;
    private javax.swing.JTextField wq_txt3;
    // End of variables declaration//GEN-END:variables
}
